import crypto from "crypto";
import { groq } from "./groq-client";
import { executeTool, getAllTools } from "../mcp/mcp-client";
import { evaluatePolicy } from "../policy/policy-engine";
import { addConversationLog, addToolLog } from "../observability/log-store";

export async function runAgent(userMessage: string) {
  addConversationLog({
    id: crypto.randomUUID(),
    userMessage,
    timestamp: new Date().toISOString(),
  });

  const toolsResponse = {
    tools: await getAllTools(),
  };
  const tools = toolsResponse.tools.map((tool) => ({
    type: "function" as const,

    function: {
      name: tool.name,
      description: tool.description || "",
      parameters: tool.inputSchema,
    },
  }));

  const completion = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",

    messages: [
      {
        role: "user",
        content: userMessage,
      },
    ],

    tools,
    tool_choice: "auto",
  });

  const message = completion.choices[0].message;

  // Fallback deterministic routing for note tools.
  // Groq tool calling can sometimes fail inconsistently so added a safe orchestration fallback

  const lowerMessage = userMessage.toLowerCase();

  if (lowerMessage.startsWith("add note")) {
    const note = userMessage.replace(/add note/i, "").trim();

    const toolResult = await executeTool("add_note", {
      note,
    });

    return {
      response: (toolResult.content as any)?.[0]?.text || "Note added",
    };
  }

  if (
    lowerMessage.includes("list my notes") ||
    lowerMessage.includes("show my notes")
  ) {
    const toolResult = await executeTool("list_notes", {});

    return {
      response: (toolResult.content as any)?.[0]?.text || "No notes found",
    };
  }

  if (message.tool_calls?.length) {
    const toolCall = message.tool_calls[0];
    if (toolCall.type !== "function") {
      throw new Error("Unsupported tool call type");
    }

    const toolName = toolCall.function.name;

    let toolArgs: Record<string, unknown> = {};

    try {
      toolArgs = JSON.parse(toolCall.function.arguments || "{}");
    } catch (error) {
      console.error("Failed to parse tool arguments:", error);

      throw new Error("Invalid tool arguments generated by model");
    }

    const policyDecision = await evaluatePolicy({
      toolName,
      arguments: toolArgs,
    });

    if (policyDecision.status === "denied") {
      return {
        response: `Tool execution blocked: ${policyDecision.reason}`,
      };
    }

    if (policyDecision.status === "requires_approval") {
      return {
        response: `Execution pending approval (${policyDecision.approvalId})`,
      };
    }

    addToolLog({
      toolName,
      arguments: toolArgs,
      timestamp: new Date().toISOString(),
    });

    const toolResult = await executeTool(toolName, toolArgs);

    const finalCompletion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",

      messages: [
        {
          role: "system",

          content:
            "You are a helpful AI agent. When using tools, ALWAYS generate valid JSON arguments matching the tool schema exactly.",
        },

        {
          role: "user",
          content: userMessage,
        },

        message,

        {
          role: "tool",

          tool_call_id: toolCall.id,

          content: JSON.stringify(toolResult.content),
        },
      ],
    });

    return {
      response: finalCompletion.choices[0].message.content,
    };
  }

  return {
    response: message.content,
  };
}
